<?php

namespace AppBundle\Repository;

/**
 * ArtsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getArts($max = 6)
{
    $qb = $this
        ->createQueryBuilder('e')
        ->addOrderBy('e.artDate', 'DESC');
        
    if ($max) {
        $qb->setMaxResults($max);
    }

    return $qb
        ->getQuery()
        ->execute()
    ;
}

}
