<?php

namespace AppBundle\Repository;

/**
 * commentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commentsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getComments($max = 4)
{
    $qb = $this
        ->createQueryBuilder('c')
        ->leftJoin('c.userId', 'u')
        ->addSelect('u')
        ->leftJoin('c.artId', 'a')
        ->addSelect('a')
        ->addOrderBy('c.commentDate', 'DESC');
        
    if ($max) {
        $qb->setMaxResults($max);
    }

    return $qb
        ->getQuery()
        ->execute()
    ;
}
}
